#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
export COPYFILE_DISABLE=1

valkyrie_root="${FPCVALKYRIE_ROOT:-/tmp/drl-fpcvalkyrie-script-test}"
if [[ ! -d "$valkyrie_root/src" || ! -d "$valkyrie_root/libs" ]]; then
  echo "Set FPCVALKYRIE_ROOT to a valid fpcvalkyrie checkout." >&2
  exit 1
fi

"$repo_root/scripts/patch-fpcvalkyrie-macos.sh" "$valkyrie_root"

version="$(head -n 1 "$repo_root/bin/version.txt" | tr -d '\r\n')"
git_short="$(git rev-parse --short HEAD)"
git_rev_dec="$((16#$git_short))"
arch="$(uname -m)"
release_name="drl-macos-${version}-${arch}"

work_dir="$repo_root/pkg/macos-release"
build_bin="$work_dir/build-bin"
build_tmp="$work_dir/build-tmp"
staging="$work_dir/$release_name"
app="$staging/DRL.app"
contents="$app/Contents"
macos="$contents/MacOS"
resources="$contents/Resources"
frameworks="$contents/Frameworks"
zip_path="$repo_root/pkg/${release_name}.zip"
sha_path="${zip_path}.sha256"

version_backup="$(mktemp)"
cp "$repo_root/src/version.inc" "$version_backup"
restore_version() {
  cp "$version_backup" "$repo_root/src/version.inc"
  rm -f "$version_backup"
}
trap restore_version EXIT

IFS=. read -r version_major version_minor version_patch _ <<< "$version"
cat > "$repo_root/src/version.inc" <<VERSION_INC
// Autogenerated by scripts/package-macos-release.sh
VERSION_STRING = '$version';
VERSION_ARRAY  : array[1..3] of byte = ($version_major,$version_minor,$version_patch);
VERSION_BETA   = false;
VERSION_REV    = $git_rev_dec;
VERSION_CORE   = 'drl';
VERSION_INC

rm -rf "$work_dir"
mkdir -p "$build_bin" "$build_tmp" "$macos" "$resources" "$frameworks"
"$repo_root/scripts/generate-macos-icon.sh" "$repo_root/src/icon.ico" "$repo_root/bin/iconfile.icns"

fpc_common=(
  "-FE$build_bin"
  "-FU$build_tmp"
  "-gl"
  "-O2"
  "-v0"
  "-Fu$valkyrie_root/src"
  "-Fu$valkyrie_root/libs"
  "-Fl/usr/local/lib"
  "-Fl/opt/homebrew/lib"
  "-Fl/opt/homebrew/opt/ncurses/lib"
  "-k-macos_version_min"
  "-k11.0"
)

fpc "$repo_root/src/drl.pas" "${fpc_common[@]}"
fpc "$repo_root/src/makewad.pas" "${fpc_common[@]}"
fpc "$repo_root/src/drlwad.pas" "${fpc_common[@]}"
rm -f "$build_tmp"/*.ppu "$build_tmp"/*.o "$build_tmp"/*.exe

(cd "$repo_root/bin" && "$build_bin/makewad")

cp "$build_bin/drl" "$macos/drl-bin"
chmod 755 "$macos/drl-bin"

for file in config.lua font.dat manual.txt unix_notes.txt version.txt version_api.txt drl.wad core.wad; do
  cp "$repo_root/bin/$file" "$resources/"
done
cp "$repo_root/bin/iconfile.icns" "$resources/iconfile.icns"
ditto --norsrc "$repo_root/bin/data" "$resources/data"
ditto --norsrc "$repo_root/bin/modules" "$resources/modules"

cat > "$macos/DRL" <<'LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail

contents="$(cd "$(dirname "$0")/.." && pwd)"
resources="$contents/Resources"
frameworks="$contents/Frameworks"
support="${HOME}/Library/Application Support/DRL"

mkdir -p "$support"
export DYLD_LIBRARY_PATH="$frameworks${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
cd "$support"

exec "$contents/MacOS/drl-bin" \
  -graphics \
  -config "$resources/config.lua" \
  -datapath "$resources/" \
  -writepath "$support/" \
  -scorepath "$support/" \
  "$@"
LAUNCHER
chmod 755 "$macos/DRL"

cat > "$contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>DRL</string>
  <key>CFBundleIconFile</key>
  <string>iconfile.icns</string>
  <key>CFBundleIdentifier</key>
  <string>org.chaosforge.drl</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>DRL</string>
  <key>CFBundleDisplayName</key>
  <string>DRL</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>$version</string>
  <key>CFBundleVersion</key>
  <string>$git_short</string>
  <key>LSMinimumSystemVersion</key>
  <string>11.0</string>
  <key>LSArchitecturePriority</key>
  <array>
    <string>$arch</string>
  </array>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
PLIST

echo "APPL????" > "$contents/PkgInfo"

copied_libs=""

lib_copied() {
  local base="$1"
  case " $copied_libs " in
    *" $base "*) return 0 ;;
    *) return 1 ;;
  esac
}

copied_count() {
  set -- $copied_libs
  echo "$#"
}

copy_lib() {
  local src="$1"
  if [[ "$src" == @rpath/* ]]; then
    local rpath_base
    rpath_base="$(basename "$src")"
    if [[ -e "/opt/homebrew/lib/$rpath_base" ]]; then
      src="/opt/homebrew/lib/$rpath_base"
    else
      local candidate
      for candidate in /opt/homebrew/opt/*/lib/"$rpath_base"; do
        if [[ -e "$candidate" ]]; then
          src="$candidate"
          break
        fi
      done
    fi
  fi

  [[ "$src" == /opt/homebrew/* ]] || return 0
  [[ -e "$src" ]] || return 0

  local base
  base="$(basename "$src")"
  if lib_copied "$base"; then
    return 0
  fi

  cp -L "$src" "$frameworks/$base"
  chmod u+w "$frameworks/$base"
  copied_libs="$copied_libs $base"
}

copy_lib "/opt/homebrew/lib/libSDL3.dylib"
copy_lib "/opt/homebrew/lib/libSDL3.0.dylib"
copy_lib "/opt/homebrew/lib/libSDL3_image.dylib"
copy_lib "/opt/homebrew/lib/libSDL3_image.0.dylib"
copy_lib "/opt/homebrew/lib/libSDL3_mixer.dylib"
copy_lib "/opt/homebrew/lib/libSDL3_mixer.0.dylib"
copy_lib "/opt/homebrew/opt/ncurses/lib/libncursesw.6.dylib"

changed=1
while [[ "$changed" -eq 1 ]]; do
  changed=0
  while IFS= read -r dylib; do
    while IFS= read -r dep; do
      before="$(copied_count)"
      copy_lib "$dep"
      after="$(copied_count)"
      if [[ "$after" -gt "$before" ]]; then
        changed=1
      fi
    done < <(otool -L "$dylib" | awk 'NR > 1 { print $1 }' | grep -E '^/opt/homebrew/|^@rpath/' || true)
  done < <(find "$frameworks" -type f -name '*.dylib' -print)
done

patch_deps() {
  local target="$1"
  local prefix="$2"
  while IFS= read -r dep; do
    install_name_tool -change "$dep" "$prefix/$(basename "$dep")" "$target" 2>/dev/null || true
  done < <(otool -L "$target" | awk 'NR > 1 { print $1 }' | grep -E '^/opt/homebrew/|^@rpath/' || true)
}

patch_deps "$macos/drl-bin" "@executable_path/../Frameworks"

while IFS= read -r dylib; do
  install_name_tool -id "@loader_path/$(basename "$dylib")" "$dylib" 2>/dev/null || true
  patch_deps "$dylib" "@loader_path"
done < <(find "$frameworks" -type f -name '*.dylib' -print)

find "$frameworks" -type f -name '*.dylib' -exec codesign --force --sign - {} \;
codesign --force --sign - "$macos/drl-bin"
codesign --force --deep --sign - "$app"

rm -f "$zip_path" "$sha_path"
ditto -c -k --norsrc --keepParent "$app" "$zip_path"
shasum -a 256 "$zip_path" > "$sha_path"

echo "$zip_path"
